from .User_Schema import UserSchema
from .Peoples_Schema import PeoplesSchema
from .Planets_Schema import PlanetsSchema
from .Vehicles_Schema import VehiclesSchema
from .Peoples_Favorite_Schema import PeoplesFavoriteSchema
from .Planets_Favorite_Schema import PlanetsFavoriteSchema
from .Vehicles_Favorite_Schema import VehiclesFavoriteSchema
from .User_Schema_Extend import UserSchemaExtend